repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: \.md$
      - id: end-of-file-fixer
        files: \.md$
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict 